name: Update docker-compose.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      jobberVersion:
        required: false
        type: string
      appVersion:
        required: false
        type: string

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - run: ./scripts/generate.sh -j ${{ inputs.jobberVersion }} -a ${{ inputs.appVersion }}