name: Update docker-compose.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      jobberVersion:
        required: false
        type: string 

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - run: echo ${{ inputs.jobberVersion }}
      # - run: ./scripts/generate.sh